include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    no_default_cases: false
    avoid_positional_boolean_parameters: false
    always_use_package_imports: false
    #always_put_required_named_parameters_first: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore   