name: riverpod_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chat_bubbles: ^1.5.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.10
  json_annotation: ^4.8.1
  supabase_flutter: ^1.8.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1
  
dependency_overrides: 
  analyzer: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - .env

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch  